// Try Catch ** Funciona para mostrar el error que se esta dando pero dejando que se ejecute el resto del codigo

const num1 = 1;
const num3 = 3;

console.log(num1);

try{
	console.log(num2);
}catch(error){
	console.log(error);
}

console.log(num3);